export const routes = {
  home: '/',
  servicios: '/servicios',
  nosotros: '/nosotros',
  contacto: '/contacto',
  blog: '/blog',
  blogPost: (slug: string) => `/blog/${slug}`,
  serviciosDetalle: (slug: string) => `/servicios/${slug}`,
  nosotrosDetalle: (slug: string) => `/nosotros/${slug}`,
  contactoDetalle: (slug: string) => `/contacto/${slug}`,
  blogDetalle: (slug: string) => `/blog/${slug}`,
  serviciosDetallePost: (slug: string, postSlug: string) =>
    `/servicios/${slug}/${postSlug}`,
  nosotrosDetallePost: (slug: string, postSlug: string) =>
    `/nosotros/${slug}/${postSlug}`,
  contactoDetallePost: (slug: string, postSlug: string) =>
    `/contacto/${slug}/${postSlug}`,
  blogDetallePost: (slug: string, postSlug: string) =>
    `/blog/${slug}/${postSlug}`,
  kitDigital: '/kit-digital',
  formacionPlataforma: '/formacion-plataforma',
  kitConsulting: '/kitconsulting',
  serviciosDigitalizacion: '/servicios/digitalizacion',
  serviciosTienda: '/servicios/tienda',
  serviciosMarketingDigital: '/servicios/marketing-digital',
  serviciosDisenioDesarrolloWeb: '/servicios/diseno-desarrollo-web',
  serviciosSeo: '/servicios/seo',
  serviciosSocialMedia: '/servicios/social-media',
  serviciosUnicoDemandaBonoPyme: '/servicios/unico-demanda-bono-pyme',
  serviciosMantenimientoWeb: '/servicios/mantenimiento-web',
  serviciosMantenimientoInformatico: '/servicios/tienda/mantenimiento-informatico',
  serviciosHardware: '/servicios/tienda/hardware',
  serviciosDigitalizacionPresenciaOnline: '/servicios/digitalizacion/presencia-online',
  serviciosDigitalizacionAnaliticaEmpresarial: '/servicios/digitalizacion/analitica-empresarial',
  serviciosDigitalizacionNegocio: '/servicios/digitalizacion/negocio',
  serviciosDigitalizacionPosicionamientoSeo: '/servicios/digitalizacion/posicionamiento-seo',
  kitDigitalPuestoTrabajoSeguro: '/kit-digital/puesto-de-trabajo-seguro',
  kitDigitalGestionProcesos: '/kit-digital/gestion-de-procesos-con-ia-asociada',
  kitDigitalCiberseguridad: '/kit-digital/ciberseguridad',
  kitDigitalGestionClientes: '/kit-digital/gestion-de-clientes-con-ia-asociada',
  kitDigitalBusinessIntelligence: '/kit-digital/business-intelligence-y-analitica-e-ia-asociada',
  kitDigitalCiberseguridadGestionada: '/kit-digital/ciberseguridad-gestionada',
  kitDigitalComunicacionesSeguras: '/kit-digital/comunicaciones-seguras',
  kitDigitalMarketplace: '/kit-digital/marketplace',
  kitDigitalFacturae: '/kit-digital/facturae',
  kitDigitalErp: '/kit-digital/erp',
  kitDigitalIntranet: '/kit-digital/intranet',
  kitDigitalBi: '/kit-digital/bi',
  kitDigitalCrm: '/kit-digital/crm',
  kitDigitalRrss: '/kit-digital/rrss',
  kitDigitalSeo: '/kit-digital/seo',
  kitDigitalEcommerce: '/kit-digital/ecommerce',
  kitDigitalWeb: '/kit-digital/web',
  formacionPlataformaPlataforma: '/formacion-plataforma/plataforma',
  kitConsultingAsesoramiento360: '/kitconsulting/servicioasesoramiento360',
  kitConsultingAsesoramientoVentasDigitales: '/kitconsulting/servicioasesoramientoventasdigitales',
  kitConsultingAsesoramientoProcesos: '/kitconsulting/servicioasesoramientoprocesos',
  kitConsultingAsesoramientoEstrategia: '/kitconsulting/servicioasesoramientoestrategia',
  kitConsultingAsesoramientoCiberCertificacion: '/kitconsulting/servicioasesoramientocibercertificacion',
  kitConsultingAsesoramientoCiberBasico: '/kitconsulting/servicioasesoramientociberbasico',
  kitConsultingAsesoramientoCiberAvanzado: '/kitconsulting/servicioasesoramientociberavanzado',
  kitConsultingAsesoramientoAdBasico: '/kitconsulting/servicioasesoramientoadbasico',
  kitConsultingAsesoramientoAdAvanzado: '/kitconsulting/servicioasesoramientoadavanzado',
  kitConsultingAsesoramientoIa: '/kitconsulting/servicioasesoramientoia',
  otrosAlmacenamientoBasico: '/almacenamiento-y-backup-en-la-nube-modalidad-basica',
  otrosAlmacenamientoAvanzado: '/almacenamiento-y-backup-en-la-nube-modalidad-avanzada',
  otrosCentralitaVirtual: '/centralita-virtual',
  otrosWifiProfesional: '/wifi-profesional',
  otrosIpFija: '/ip-fija',
  otrosAnysFalla: '/50anysfalla',
  otrosCMFast: '/cmfast',
  otrosCMMopy: '/cmmopy',
  otrosCreaComer: '/creacomer',
  otrosRGPD: '/rgpd',
  otrosDolibarrERP: '/dolibarr-erp-crm-codigo-abierto',
  otrosMasterDigitalizacion: '/master-digitalizacion',
  otrosGestionSubvenciones: '/gestion-de-subvenciones',
  otrosOnline: '/online',
  otrosPresupuesto: '/presupuesto',
  otrosExeOrg: '/exe-org',
  otrosExeCrm: '/exe-crm',
} as const 